=== nicrausaz/tb-modularapp/packages/rfid-composal-stamp/src/schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$ref": "#/definitions/module",
  "definitions": {
    "module": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "$schema": {
          "type": "string"
        },
        "name": {
          "type": "string",
          "minLength": 2
        },
        "description": {
          "type": "string",
          "minLength": 2
        },
        "version": {
          "type": "string",
          "minLength": 1
        },
        "author": {
          "type": "string",
          "minLength": 2
        },
        "icon": {
          "type": "string"
        },
        "requires": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "specificConfig": {
          "$ref": "#/definitions/SpecificConfig"
        }
      },
      "required": ["author", "description", "icon", "name", "requires", "specificConfig", "version"],
      "title": "Module"
    },
    "SpecificConfig": {
      "type": "object",
      "additionalProperties": true,
      "title": "SpecificConfig",
      "properties": {
        "^[a-zA-Z0-9]+$": {
          "$ref": "#/definitions/SpecificConfigEntry"
        }
      }
    },
    "SpecificConfigEntry": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string"
        },
        "label": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "options": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": ["description", "label", "type", "value"],
      "title": "SpecificConfigEntry"
    }
  }
}

=== nicrausaz/tb-modularapp/packages/module-example/src/config.json
{
  "$schema": "https://test.crausaz.click/schema.json",
  "name": "Example Module",
  "description": "Template for easily creating your custom intergrations for the modular app",
  "version": "1.0.0",
  "author": "Nicolas Crausaz",
  "icon": "icon.svg",
  "requires": ["http", "keyboard"],
  "specificConfig": {
    "anExampleText": {
      "type": "text",
      "label": "Example value",
      "description": "An example value for a text",
      "value": "A base value"
    },
    "anExampleNumber": {
      "type": "number",
      "label": "Example number",
      "description": "An example value for a number",
      "value": 42
    },
    "anExampleBool": {
      "type": "bool",
      "label": "Example boolean",
      "description": "An example value for a boolean",
      "value": true
    },
    "anExampleOption": {
      "type": "option",
      "label": "Example select",
      "description": "An example value for a select",
      "value": "option1",
      "options": ["option1", "option2", "option3"]
    },
    "anExampleSecret": {
      "type": "secret",
      "label": "Example secret",
      "description": "An example value for a secret",
      "value": "secret"
    }
  }
}

=== nicrausaz/tb-modularapp/packages/rfid-composal-stamp/src/config.json
{
  "$schema": "https://test.crausaz.click/schema.json",
  "name": "Composal Badging",
  "description": "Module allowing users to scan their badge through a RFID reader to clock in and out",
  "version": "1.0.0",
  "author": "Nicolas Crausaz",
  "icon": "composal.svg",
  "requires": ["http", "keyboard"],
  "specificConfig": {
    "authToken": {
      "type": "secret",
      "label": "Authentication token",
      "description": "The Bearer token used to authenticate the request",
      "value": "NUYC7IzclxqvGI3NyTKrzApO379nmeAyDE-2BYci_H6-MYugWyzqRFm362LHiTb1"
    },
    "composalUrl": {
      "type": "text",
      "label": "Composal URL",
      "description": "The URL of the your Composal instance",
      "value": "https://yalk-composal-nico.herokuapp.com/api/badging/toggle"
    }
  }
}
